Repository prgrms-web-devcourse-final-project/WEB2_3_SIGNAL-BUDDY_BE, pull requests merged in 2025-03, with the labels that each got.

#104 [Feature] 소셜 로그인 기능 구현
  src/main/java/org/programmers/signalbuddyfinal/domain/auth/controller/AuthController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/auth/dto/SocialLoginRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/auth/service/AuthService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/repository/MemberRepository.java
  src/main/java/org/programmers/signalbuddyfinal/global/config/SecurityConfig.java
  src/main/java/org/programmers/signalbuddyfinal/global/security/CustomAuthenticationProvider.java
  src/main/java/org/programmers/signalbuddyfinal/global/security/filter/JwtAuthorizationFilter.java
  src/test/java/org/programmers/signalbuddyfinal/domain/auth/controller/AuthControllerTest.java
Labels: Feature

#107 [Feature] 비밀번호 재설정 기능 추가
  src/main/java/org/programmers/signalbuddyfinal/domain/auth/exception/AuthErrorCode.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/dto/ResetPasswordRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/service/MemberService.java
  src/main/java/org/programmers/signalbuddyfinal/global/config/AsyncConfig.java
  src/main/java/org/programmers/signalbuddyfinal/global/config/SecurityConfig.java
  src/main/java/org/programmers/signalbuddyfinal/global/security/filter/JwtAuthorizationFilter.java
  src/test/java/org/programmers/signalbuddyfinal/domain/auth/controller/AuthControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberControllerTest.java
Labels: Feature

#110 [Feature] 보행등 정보 저장하기
  build.gradle
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/controller/CrossroadController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/dto/CrossroadApiResponse.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postit/entity/Postit.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postit/service/PostItService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/trafficSignal/controller/TrafficController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/trafficSignal/dto/TrafficFileResponse.java
  src/main/java/org/programmers/signalbuddyfinal/domain/trafficSignal/entity/TrafficSignal.java
  src/main/java/org/programmers/signalbuddyfinal/domain/trafficSignal/exception/TrafficErrorCode.java
  src/main/java/org/programmers/signalbuddyfinal/domain/trafficSignal/repository/TrafficRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/trafficSignal/service/TrafficCsvService.java
  src/main/java/org/programmers/signalbuddyfinal/global/util/PointUtil.java
  src/main/resources/static/file/seoul_traffic_light.csv
  src/main/resources/static/file/seoul_traffic_light_test.csv
  src/test/java/org/programmers/signalbuddyfinal/SignalBuddyFinalApplicationTests.java
  src/test/java/org/programmers/signalbuddyfinal/domain/admin/repository/AdminPostItRepositoryTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/admin/service/AdminPostItServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/postit/service/PostItServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/traffic/controller/TrafficControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/traffic/service/TrafficCsvServiceTest.java
Labels: Feature, Test

#111 [Feature] 소셜 회원가입 기능 추가
  build.gradle
  src/main/java/org/programmers/signalbuddyfinal/domain/admin/dto/AdminMemberResponse.java
  src/main/java/org/programmers/signalbuddyfinal/domain/admin/dto/MemberFilterRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/auth/dto/SocialLoginRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/dto/MemberJoinRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/exception/MemberErrorCode.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/repository/CustomMemberRepositoryImpl.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/repository/MemberRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/service/MemberService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/social/entity/Provider.java
  src/main/java/org/programmers/signalbuddyfinal/domain/social/entity/SocialProvider.java
  src/main/java/org/programmers/signalbuddyfinal/domain/social/repository/SocialProviderRepository.java
  src/main/java/org/programmers/signalbuddyfinal/global/dto/CustomUser2Member.java
  src/main/java/org/programmers/signalbuddyfinal/global/exception/advice/GlobalExceptionHandler.java
  src/main/java/org/programmers/signalbuddyfinal/global/security/oauth/CustomOAuth2User.java
  src/main/java/org/programmers/signalbuddyfinal/global/security/oauth/CustomOAuth2UserService.java
  src/main/java/org/programmers/signalbuddyfinal/global/security/oauth/response/GoogleResponse.java
  src/main/java/org/programmers/signalbuddyfinal/global/security/oauth/response/KakaoResponse.java
  src/main/java/org/programmers/signalbuddyfinal/global/security/oauth/response/NaverResponse.java
  src/main/java/org/programmers/signalbuddyfinal/global/security/oauth/response/OAuth2Response.java
  src/test/java/org/programmers/signalbuddyfinal/domain/admin/controller/AdminMemberControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/admin/repository/AdminMemberRepositoryTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/admin/service/AdminMemberServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/auth/controller/AuthControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberControllerTest.java
Labels: Feature

#115 [Refactor] 시퀀스 변경 로직 수정
  src/main/java/org/programmers/signalbuddyfinal/domain/bookmark/service/BookmarkService.java
Labels: Bug, Refactor

#116 [Feature] 계정 복구 기능 구현
  src/main/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/dto/MemberRestoreRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/entity/Member.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/service/MemberService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postit_report/entity/PostItReport.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postitsolve/entity/PostitSolve.java
  src/main/java/org/programmers/signalbuddyfinal/global/config/SecurityConfig.java
  src/main/java/org/programmers/signalbuddyfinal/global/security/filter/JwtAuthorizationFilter.java
  src/test/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberControllerTest.java
Labels: Feature

#120 [Feature] 메인 신호등 상태 정보 캐싱
  build.gradle
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/controller/CrossroadController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/dto/CrossroadStateApiResponse.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/dto/CrossroadStateResponse.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/dto/SignalState.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/mapper/CrossroadMapper.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/service/CrossroadProvider.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/service/CrossroadService.java
  src/main/java/org/programmers/signalbuddyfinal/global/config/RedisConfig.java
  src/main/java/org/programmers/signalbuddyfinal/global/security/filter/JwtAuthorizationFilter.java
  src/test/java/org/programmers/signalbuddyfinal/domain/crossroad/controller/CrossroadControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/crossroad/service/CrossroadProviderTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/crossroad/service/CrossroadServiceTest.java
  src/test/resources/response/crossroad_location_api.json
  src/test/resources/response/crossroad_state_api.json
Labels: Chore, Feature, Test

#121 [Feature] 소켓 통신 기능 구현
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/dto/CrossroadResponse.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/dto/LocationRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/handler/CrossroadWebSocketHandler.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/repository/CustomCrossroadRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/repository/CustomCrossroadRepositoryImpl.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/service/CrossroadService.java
  src/main/java/org/programmers/signalbuddyfinal/global/config/WebSocketConfig.java
  src/main/java/org/programmers/signalbuddyfinal/global/handler/CustomWebSocketHandler.java
  src/test/java/org/programmers/signalbuddyfinal/domain/crossroad/handler/CrossroadWebSocketHandlerTest.java
Labels: Feature, Test

#125 [Feature] 관리자 회원가입 기능 추가
  src/main/java/org/programmers/signalbuddyfinal/domain/admin/controller/AdminController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/admin/dto/AdminJoinRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/admin/service/AdminService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/service/MemberService.java
  src/test/java/org/programmers/signalbuddyfinal/domain/admin/controller/AdminControllerTest.java
Labels: Feature

#123 [Refactor] reissue액세스토큰 검증 추가
  src/main/java/org/programmers/signalbuddyfinal/domain/auth/controller/AuthController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/auth/service/AuthService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/service/MemberService.java
  src/main/java/org/programmers/signalbuddyfinal/global/config/SecurityConfig.java
  src/main/java/org/programmers/signalbuddyfinal/global/security/filter/JwtAuthorizationFilter.java
  src/main/java/org/programmers/signalbuddyfinal/global/security/jwt/JwtService.java
  src/main/java/org/programmers/signalbuddyfinal/global/security/jwt/JwtUtil.java
  src/test/java/org/programmers/signalbuddyfinal/domain/auth/controller/AuthControllerTest.java
Labels: Refactor

#127 [Feature] 로그아웃 기능 추가
  src/main/java/org/programmers/signalbuddyfinal/domain/auth/controller/AuthController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/auth/service/AuthService.java
  src/main/java/org/programmers/signalbuddyfinal/global/security/jwt/JwtService.java
  src/test/java/org/programmers/signalbuddyfinal/domain/auth/controller/AuthControllerTest.java
Labels: Feature

#138 [Feature] 피드백 댓글 알림 기능
  src/main/java/org/programmers/signalbuddyfinal/domain/comment/service/CommentService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/notification/service/FcmService.java
  src/test/java/org/programmers/signalbuddyfinal/domain/comment/service/CommentServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/notification/service/FcmServiceTest.java
Labels: Feature

#140 [Refactor] 길찾기 기능 요청 값 변경
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/dto/NavigationRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/handler/MapWebSocketHandler.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/handler/NavigationWebSocketHandler.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/repository/CrossroadRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/repository/CustomCrossroadRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/repository/CustomCrossroadRepositoryImpl.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/service/CrossroadService.java
  src/test/java/org/programmers/signalbuddyfinal/domain/crossroad/handler/NavigationWebSocketHandlerTest.java
Labels: Feature, Refactor, Test

#139 [Refactor] 로그인 실패 시, 응답값 변경
  src/main/java/org/programmers/signalbuddyfinal/domain/auth/controller/AuthController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/auth/service/AuthService.java
  src/test/java/org/programmers/signalbuddyfinal/domain/auth/controller/AuthControllerTest.java
Labels: Refactor

#144 [Feature] 알림 사용자 기기 복수 등록
  jenkins/develop.jenkinsfile
  src/main/java/org/programmers/signalbuddyfinal/domain/notification/controller/FcmController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/notification/entity/FcmToken.java
  src/main/java/org/programmers/signalbuddyfinal/domain/notification/repository/FcmTokenRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/notification/service/FcmService.java
  src/test/java/org/programmers/signalbuddyfinal/domain/notification/controller/FcmControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/notification/service/FcmServiceTest.java
Labels: Feature

#146 [Feature] 알림 계정별 알림 설정 유무
  src/main/java/org/programmers/signalbuddyfinal/domain/comment/service/CommentService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/dto/MemberNotiAllowRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/dto/MemberResponse.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/entity/Member.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/exception/MemberErrorCode.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/service/MemberService.java
  src/main/java/org/programmers/signalbuddyfinal/global/security/filter/JwtAuthorizationFilter.java
  src/test/java/org/programmers/signalbuddyfinal/domain/comment/service/CommentServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/member/service/MemberServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/global/support/RestDocsFormatGenerators.java
Labels: Bug, Feature, Refactor

#161 [Featuer] 최근 경로에 필드 추가
  src/main/java/org/programmers/signalbuddyfinal/domain/recentpath/dto/RecentPathRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/recentpath/dto/RecentPathResponse.java
  src/main/java/org/programmers/signalbuddyfinal/domain/recentpath/entity/RecentPath.java
  src/test/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/recentpath/controller/RecentPathControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/recentpath/service/RecentPathServiceTest.java
Labels: Feature

#163 [Bug] 최근경로 저장 버그
  src/main/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/recentpath/entity/RecentPath.java
  src/test/java/org/programmers/signalbuddyfinal/domain/recentpath/service/RecentPathServiceTest.java
Labels: Bug

#165 Refactor/#164 최근경로 북마크 연관관계 설정
  src/main/java/org/programmers/signalbuddyfinal/domain/recentpath/controller/RecentPathController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/recentpath/dto/RecentPathLinkRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/recentpath/service/RecentPathService.java
  src/test/java/org/programmers/signalbuddyfinal/domain/recentpath/controller/RecentPathControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/recentpath/service/RecentPathServiceTest.java
Labels: Refactor, Test

#167 [Feature] 유저가 좋아요한 피드백 목록 조회
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/service/FeedbackService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/like/repository/CustomLikeRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/like/repository/CustomLikeRepositoryImpl.java
  src/main/java/org/programmers/signalbuddyfinal/domain/like/repository/LikeRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberController.java
  src/test/java/org/programmers/signalbuddyfinal/domain/feedback/service/FeedbackServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberControllerTest.java
Labels: Feature, Test

#169 [Refactor] 교차로 데이터의 상태 타입 변경
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/controller/CrossroadController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/dto/CrossroadResponse.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/entity/Crossroad.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/repository/CrossroadRedisRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/service/CrossroadService.java
  src/test/java/org/programmers/signalbuddyfinal/domain/crossroad/handler/MapWebSocketHandlerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/crossroad/service/CrossroadServiceLocationTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/feedback/controller/FeedbackControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/unifiedSignal/controller/SignalControllerTest.java
Labels: Refactor, Style

#172 [Feature] 피드백 댓글 알림에 데이터 추가
  src/main/java/org/programmers/signalbuddyfinal/domain/comment/service/CommentService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/notification/dto/FcmMessage.java
  src/main/java/org/programmers/signalbuddyfinal/domain/notification/service/FcmService.java
  src/test/java/org/programmers/signalbuddyfinal/domain/notification/service/FcmServiceTest.java
Labels: Feature, Refactor

#173 [Refactor] 최근경로 로직 수정
  src/main/java/org/programmers/signalbuddyfinal/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/bookmark/repository/BookmarkRepositoryCustom.java
  src/main/java/org/programmers/signalbuddyfinal/domain/bookmark/repository/BookmarkRepositoryCustomImpl.java
  src/main/java/org/programmers/signalbuddyfinal/domain/bookmark/service/BookmarkService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/recentpath/repository/RecentPathRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/recentpath/service/RecentPathService.java
  src/test/java/org/programmers/signalbuddyfinal/domain/recentpath/service/RecentPathServiceTest.java
Labels: Refactor, Test

#176 [Refactor] 웹소켓 경로 체크 부분 수정
  src/main/java/org/programmers/signalbuddyfinal/global/security/filter/JwtAuthorizationFilter.java
Labels: Refactor

#178 [Feature] 주변 교차로 알림
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/handler/MapWebSocketHandler.java
  src/test/java/org/programmers/signalbuddyfinal/domain/crossroad/handler/MapWebSocketHandlerTest.java
Labels: Feature

#181 [Refactor] 사용자 기본 프로필 이미지 변경
  src/main/java/org/programmers/signalbuddyfinal/global/service/DefaultProfileImageInitializer.java
  src/main/resources/static/images/member/new-profile-icon.png
  src/main/resources/static/images/member/old-profile-icon.png
  src/test/java/org/programmers/signalbuddyfinal/global/service/DefaultProfileImageInitializerTest.java
Labels: Refactor, Test

#180 [Refactor] 신호등 상태 api 필드 추가
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/dto/CrossroadStateResponse.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/mapper/CrossroadMapper.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/service/CrossroadService.java
  src/test/java/org/programmers/signalbuddyfinal/domain/crossroad/controller/CrossroadControllerTest.java
Labels: Refactor

#183 [Bug] 북마크 중복 생성
  src/main/java/org/programmers/signalbuddyfinal/domain/bookmark/exception/BookmarkErrorCode.java
  src/main/java/org/programmers/signalbuddyfinal/domain/bookmark/service/BookmarkService.java
  src/test/java/org/programmers/signalbuddyfinal/domain/bookmark/service/BookmarkServiceTest.java
Labels: Bug

#184 [Refactor] jwt filter 수정
  src/main/java/org/programmers/signalbuddyfinal/global/security/filter/JwtAuthorizationFilter.java
Labels: Bug

#189 [Refactor] 북마크 수정 시 최근경로 필드 업데이트
  src/main/java/org/programmers/signalbuddyfinal/domain/bookmark/service/BookmarkService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/recentpath/entity/RecentPath.java
  src/main/java/org/programmers/signalbuddyfinal/domain/recentpath/repository/RecentPathRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/recentpath/service/RecentPathService.java
  src/test/java/org/programmers/signalbuddyfinal/domain/bookmark/service/BookmarkServiceTest.java
Labels: Refactor

#194 [Bug] 북마크 조회 오류
  src/main/java/org/programmers/signalbuddyfinal/domain/bookmark/repository/BookmarkRepositoryCustomImpl.java
Labels: Bug

#198 [Refactor] 디바이스 토큰 쿠키
  src/main/java/org/programmers/signalbuddyfinal/domain/auth/controller/AuthController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/auth/service/AuthService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/notification/controller/FcmController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/notification/entity/FcmToken.java
  src/main/java/org/programmers/signalbuddyfinal/domain/notification/exception/FcmErrorCode.java
  src/main/java/org/programmers/signalbuddyfinal/domain/notification/repository/FcmTokenRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/notification/service/FcmService.java
  src/main/java/org/programmers/signalbuddyfinal/global/config/SecurityConfig.java
  src/main/java/org/programmers/signalbuddyfinal/global/security/filter/JwtAuthorizationFilter.java
  src/test/java/org/programmers/signalbuddyfinal/domain/auth/controller/AuthControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/notification/controller/FcmControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/notification/service/FcmServiceTest.java
Labels: Feature, Refactor

#207 [Refactor] 설정 사항 변경
  README.md
  build.gradle
  src/main/java/org/programmers/signalbuddyfinal/domain/like/batch/LikeBatchLogJobConfig.java
Labels: Chore, Docs
