Repository prgrms-web-devcourse-final-project/WEB2_3_SIGNAL-BUDDY_BE, pull requests merged in 2025-05, with the labels that each got.

#236 [Refactor] 좋아요 캐싱 로직 분리
  src/main/java/org/programmers/signalbuddyfinal/domain/like/batch/RequestLikeReader.java
  src/main/java/org/programmers/signalbuddyfinal/domain/like/batch/RequestLikeWriter.java
  src/main/java/org/programmers/signalbuddyfinal/domain/like/dto/LikeExistResponse.java
  src/main/java/org/programmers/signalbuddyfinal/domain/like/service/LikeCacheService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/like/service/LikeService.java
  src/test/java/org/programmers/signalbuddyfinal/domain/like/service/LikeServiceTest.java
Labels: Refactor

#237 [Refactor] 인증인가 테스트코드 리팩토링
  src/main/java/org/programmers/signalbuddyfinal/global/security/jwt/JwtUtil.java
  src/test/java/org/programmers/signalbuddyfinal/domain/auth/service/AuthServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/global/security/jwt/JwtServiceTest.java
Labels: Refactor, Test

#240 [Refactor] 북마크 리팩터링 진행
  src/main/java/org/programmers/signalbuddyfinal/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/bookmark/service/BookmarkService.java
  src/test/java/org/programmers/signalbuddyfinal/domain/bookmark/service/BookmarkServiceTest.java
Labels: Refactor, Test

#242 [Refactor] 날씨 기능 리팩터링
  src/main/java/org/programmers/signalbuddyfinal/domain/weather/service/WeatherService.java
Labels: Refactor

#243 [Fix] 이메일 관련 로직 수정
  src/main/java/org/programmers/signalbuddyfinal/domain/auth/controller/AuthController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/auth/service/AuthService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/auth/service/EmailService.java
  src/main/java/org/programmers/signalbuddyfinal/global/security/jwt/RefreshTokenRepository.java
  src/test/java/org/programmers/signalbuddyfinal/domain/auth/controller/AuthControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/auth/service/AuthServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/auth/service/EmailServiceTest.java
Labels: Bug, Test

#246 [Fix] 날씨 요청 타임존 설정 및 로그 추가
  src/main/java/org/programmers/signalbuddyfinal/domain/weather/service/WeatherProvider.java
  src/main/java/org/programmers/signalbuddyfinal/domain/weather/service/WeatherService.java
Labels: Bug

#247 [Fix] ZoneId 추가
  src/main/java/org/programmers/signalbuddyfinal/domain/weather/service/WeatherProvider.java
Labels: Bug

#251 [Fix] 이메일 전송 테스트 대기 시간 연장
  src/test/java/org/programmers/signalbuddyfinal/domain/auth/service/EmailServiceTest.java
Labels: Bug, Test

#253 [Refactor] 메서드 매개변수 목록 간략화
  src/main/java/org/programmers/signalbuddyfinal/domain/admin/dto/AdminSearchCondition.java
  src/main/java/org/programmers/signalbuddyfinal/domain/admin/service/AdminFeedbackService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/dto/FeedbackSearchCondition.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/repository/CustomFeedbackRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/repository/CustomFeedbackRepositoryImpl.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/service/FeedbackService.java
  src/test/java/org/programmers/signalbuddyfinal/domain/admin/service/AdminFeedbackServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/feedback/repository/FeedbackRepositoryImplTest.java
Labels: Refactor

#257 [Refactor] commentService unit test로 변경
  src/test/java/org/programmers/signalbuddyfinal/domain/admin/service/AdminFeedbackServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/admin/service/AdminMemberServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/admin/service/AdminPostItServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/air_quality/service/AirQualityServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/auth/service/AuthServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/auth/service/EmailServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/bookmark/service/BookmarkServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/comment/service/CommentServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/crossroad/service/CrossroadServiceLocationTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/crossroad/service/CrossroadServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/feedback/service/FeedbackServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/feedback_report/service/FeedbackReportServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/feedback_summary/repository/CustomFeedbackSummaryRepositoryImplTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/feedback_summary/service/FeedbackSummaryServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/like/service/LikeServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/member/service/MemberServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/notification/service/FcmServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/postit/service/PostItServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/recentpath/service/RecentPathServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/traffic/service/TrafficCsvServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/traffic/service/TrafficServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/weather/service/WeatherServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/global/support/BatchTest.java
  src/test/java/org/programmers/signalbuddyfinal/global/support/IntegrationTest.java
  src/test/java/org/programmers/signalbuddyfinal/global/support/ServiceTest.java
Labels: Refactor, Test

#264 [Refactor] 긴 조건문 리팩터링
  src/main/java/org/programmers/signalbuddyfinal/domain/comment/service/CommentService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/notification/factory/CommentNotificationFactory.java
  src/test/java/org/programmers/signalbuddyfinal/domain/comment/service/CommentServiceTest.java
Labels: Refactor
