Repository prgrms-web-devcourse-final-project/WEB2_3_SIGNAL-BUDDY_BE, pull requests merged in 2025-04, with the labels that each got.

#205 [Feature] 좋아요 여부 확인 로직 추가
  src/main/java/org/programmers/signalbuddyfinal/domain/like/dto/LikeExistResponse.java
  src/main/java/org/programmers/signalbuddyfinal/domain/like/dto/LikeUpdateRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/like/exception/LikeErrorCode.java
  src/main/java/org/programmers/signalbuddyfinal/domain/like/service/LikeService.java
  src/test/java/org/programmers/signalbuddyfinal/domain/like/service/LikeServiceTest.java
Labels: Feature, Test

#209 [Refactor] crossrad entity 코드 리팩토링
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/dto/CrossroadApiResponse.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/dto/CrossroadResponse.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/entity/Crossroad.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/mapper/CrossroadMapper.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/service/CrossroadService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postit/entity/Postit.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postit/service/PostItService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/trafficSignal/dto/TrafficFileResponse.java
  src/main/java/org/programmers/signalbuddyfinal/domain/trafficSignal/dto/TrafficResponse.java
  src/main/java/org/programmers/signalbuddyfinal/global/util/PointUtils.java
  src/test/java/org/programmers/signalbuddyfinal/domain/admin/repository/AdminPostItRepositoryTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/admin/service/AdminPostItServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/comment/repository/CommentRepositoryTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/comment/service/CommentServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/crossroad/service/CrossroadServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/feedback/repository/FeedbackRepositoryImplTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/feedback/service/FeedbackServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/feedback_report/repository/FeedbackReportRepositoryTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/feedback_report/service/FeedbackReportServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/feedback_summary/batch/FeedbackSummaryTaskletTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/feedback_summary/repository/CustomFeedbackSummaryRepositoryImplTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/like/batch/LikeJobConfigTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/like/service/LikeServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/postit/service/PostItServiceTest.java
Labels: Refactor

#212 [Refactor] 코드 커버리지 높이기
  src/main/java/org/programmers/signalbuddyfinal/domain/admin/service/AdminFeedbackService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/controller/CrossroadController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/repository/CrossroadRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/service/CrossroadService.java
  src/test/java/org/programmers/signalbuddyfinal/domain/admin/service/AdminFeedbackServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/crossroad/service/CrossroadServiceTest.java
Labels: Refactor, Test

#218 [Refactor] 교차로 캐싱 로직 분리
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/entity/Crossroad.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/service/CrossroadCacheService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/service/CrossroadService.java
Labels: Refactor

#222 [Fix] #213 미세먼지 구현
  src/main/java/org/programmers/signalbuddyfinal/global/config/SecurityConfig.java
Labels: Feature, Refactor

#228 [Fix] Jenkins 배포 실패
  jenkins/develop.jenkinsfile
  jenkins/main.jenkinsfile
Labels: Bug, CD

#226 [Refactor] 북마크 테스트 코드 수정
  src/main/java/org/programmers/signalbuddyfinal/domain/bookmark/entity/Bookmark.java
  src/main/java/org/programmers/signalbuddyfinal/domain/bookmark/service/BookmarkService.java
  src/test/java/org/programmers/signalbuddyfinal/domain/bookmark/service/BookmarkServiceTest.java
Labels: Refactor, Test

#232 [Test] 회원가입 테스트 코드 작성
  src/main/java/org/programmers/signalbuddyfinal/domain/member/dto/MemberJoinRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/service/MemberService.java
  src/test/java/org/programmers/signalbuddyfinal/domain/member/service/MemberServiceTest.java
Labels: Test

#234 [Refactor] 미세먼지 API 리팩터링
  src/main/java/org/programmers/signalbuddyfinal/domain/air_quality/dto/AirQualityResponse.java
  src/main/java/org/programmers/signalbuddyfinal/domain/air_quality/service/AirQualityService.java
  src/test/java/org/programmers/signalbuddyfinal/domain/air_quality/service/AirQualityServiceTest.java
Labels: Refactor
