Repository prgrms-web-devcourse-final-project/WEB2_3_SIGNAL-BUDDY_BE, pull requests merged in 2025-02, with the labels that each got.

#14 [Feat] 공통 Response 클래스 추가
  src/main/java/org/programmers/signalbuddyfinal/global/constant/ResponseStatus.java
  src/main/java/org/programmers/signalbuddyfinal/global/response/ApiResponse.java
Labels: Feature

#23 [Feature] 좋아요 기능
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/entity/Feedback.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/entity/enums/FeedbackCategory.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/service/FeedbackService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/like/batch/LikeBatchLogJobConfig.java
  src/main/java/org/programmers/signalbuddyfinal/domain/like/batch/LikeJobConfig.java
  src/main/java/org/programmers/signalbuddyfinal/domain/like/batch/LikeJobScheduler.java
  src/main/java/org/programmers/signalbuddyfinal/domain/like/batch/LikeLogDeleteJobScheduler.java
  src/main/java/org/programmers/signalbuddyfinal/domain/like/batch/RequestLikeReader.java
  src/main/java/org/programmers/signalbuddyfinal/domain/like/batch/RequestLikeWriter.java
  src/main/java/org/programmers/signalbuddyfinal/domain/like/repository/LikeRepository.java
  src/main/java/org/programmers/signalbuddyfinal/global/batch/dto/BatchExecutionId.java
  src/main/java/org/programmers/signalbuddyfinal/global/batch/job/BatchLogJob.java
  src/main/java/org/programmers/signalbuddyfinal/global/batch/job/BatchLogJobScheduler.java
  src/main/java/org/programmers/signalbuddyfinal/global/batch/job/OldLogDeleteTasklet.java
  src/main/java/org/programmers/signalbuddyfinal/global/batch/repository/BatchJdbcRepository.java
  src/test/java/org/programmers/signalbuddyfinal/domain/comment/repository/CommentRepositoryTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/comment/service/CommentServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/feedback/repository/FeedbackJdbcRepositoryTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/feedback/repository/FeedbackRepositoryTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/feedback/service/FeedbackServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/like/batch/LikeBatchLogJobConfigTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/like/batch/LikeJobConfigTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/like/batch/LikeJobSchedulerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/like/batch/LikeLogDeleteJobSchedulerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/like/service/LikeServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/global/batch/job/BatchLogJobSchedulerTest.java
  src/test/java/org/programmers/signalbuddyfinal/global/batch/job/BatchLogJobTest.java
  src/test/resources/application-test.yml
Labels: Chore, Feature

#30 [Feature] 피드백 댓글 기능
  jenkins/develop.jenkinsfile
  src/main/java/org/programmers/signalbuddyfinal/domain/comment/controller/CommentController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/comment/dto/CommentRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/comment/entity/Comment.java
  src/main/java/org/programmers/signalbuddyfinal/domain/comment/repository/CommentRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/comment/repository/CustomCommentRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/comment/repository/CustomCommentRepositoryImpl.java
  src/main/java/org/programmers/signalbuddyfinal/domain/comment/service/CommentService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/service/FeedbackService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/entity/Member.java
  src/main/java/org/programmers/signalbuddyfinal/global/config/SecurityConfig.java
  src/test/java/org/programmers/signalbuddyfinal/domain/comment/controller/CommentControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/comment/repository/CommentRepositoryTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/comment/service/CommentServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/global/support/RestDocsFormatGenerators.java
Labels: Feature

#32 [Feature] 마이페이지 계정 관련 기능 추가
  src/main/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/dto/MemberUpdateRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/entity/Member.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/service/MemberService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/trafficSignal/entity/TrafficSignal.java
  src/main/resources/static/images/member/profile-icon.png
  src/test/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/member/service/MemberServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/global/support/RestDocsFormatGenerators.java
Labels: Feature

#34 [Feature] 자신이 쓴 글 목록 조회 기능 추가
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/dto/FeedbackResponse.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/repository/CustomFeedbackRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/repository/CustomFeedbackRepositoryImpl.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/service/FeedbackService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberController.java
  src/test/java/org/programmers/signalbuddyfinal/domain/feedback/repository/FeedbackRepositoryImplTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/feedback/service/FeedbackServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberControllerTest.java
Labels: Feature, Test

#42 [Fix] 젠킨스 서버 부하 줄이기
  .github/workflows/docker-build.yaml
  jenkins/develop.jenkinsfile
Labels: Bug, CD

#43 [Fix] jenkins 서버 과부하2
  .github/workflows/docker-build.yaml
Labels: Bug, CD

#47 [Feature] 나의장소 최근경로 구현
  src/main/java/org/programmers/signalbuddyfinal/domain/bookmark/dto/BookmarkResponse.java
  src/main/java/org/programmers/signalbuddyfinal/domain/bookmark/dto/BookmarkSequenceUpdateRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/bookmark/entity/Bookmark.java
  src/main/java/org/programmers/signalbuddyfinal/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/bookmark/repository/BookmarkRepositoryCustomImpl.java
  src/main/java/org/programmers/signalbuddyfinal/domain/bookmark/service/BookmarkService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/service/MemberService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postitsolve/entity/PostitSolve.java
  src/main/java/org/programmers/signalbuddyfinal/domain/recentPath/entity/RecentPath.java
  src/main/java/org/programmers/signalbuddyfinal/domain/recentpath/controller/RecentPathController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/recentpath/dto/RecentPathRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/recentpath/dto/RecentPathResponse.java
  src/main/java/org/programmers/signalbuddyfinal/domain/recentpath/entity/RecentPath.java
  src/main/java/org/programmers/signalbuddyfinal/domain/recentpath/exception/RecentPathErrorCode.java
  src/main/java/org/programmers/signalbuddyfinal/domain/recentpath/mapper/RecentPathMapper.java
  src/main/java/org/programmers/signalbuddyfinal/domain/recentpath/repository/RecentPathRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/recentpath/service/RecentPathService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/trafficsignal/entity/TrafficSignal.java
  src/test/java/org/programmers/signalbuddyfinal/domain/bookmark/repository/BookmarkRepositoryTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/bookmark/service/BookmarkServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/member/service/MemberServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/recentpath/controller/RecentPathControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/recentpath/repository/RecentPathRepositoryTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/recentpath/service/RecentPathServiceTest.java
Labels: Docs, Feature, Test

#50 [Feature] 일반 사용자에 대한 피드백 기능
  jenkins/develop.jenkinsfile
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/dto/CrossroadResponse.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/exception/CrossroadErrorCode.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/repository/CrossroadRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/repository/CustomCrossroadRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/repository/CustomCrossroadRepositoryImpl.java
  src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/service/CrossroadService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/controller/FeedbackController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/dto/FeedbackMapper.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/dto/FeedbackRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/dto/FeedbackResponse.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/dto/FeedbackWriteRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/entity/Feedback.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/entity/enums/AnswerStatus.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/entity/enums/FeedbackCategory.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/exception/FeedbackErrorCode.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/mapper/AnswerStatusConverter.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/mapper/FeedbackCategoryConverter.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/mapper/FeedbackMapper.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/repository/CustomFeedbackRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/repository/CustomFeedbackRepositoryImpl.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/service/FeedbackService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/entity/Member.java
  src/main/java/org/programmers/signalbuddyfinal/global/config/CustomMariaDbFunctionContributor.java
  src/main/java/org/programmers/signalbuddyfinal/global/config/SecurityConfig.java
  src/main/java/org/programmers/signalbuddyfinal/global/exception/advice/GlobalExceptionHandler.java
  src/main/resources/META-INF/services/org.hibernate.boot.model.FunctionContributor
  src/test/java/org/programmers/signalbuddyfinal/domain/comment/controller/CommentControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/feedback/controller/FeedbackControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/feedback/repository/FeedbackRepositoryImplTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/feedback/service/FeedbackServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/like/controller/LikeControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/global/support/RestDocsFormatGenerators.java
Labels: Docs, Feature, Refactor

#56 [Feature] 기본 회원가입 기능 구현
  src/main/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/dto/MemberJoinRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/exception/MemberErrorCode.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/repository/MemberRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/service/MemberService.java
  src/test/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/member/service/MemberServiceTest.java
Labels: Feature

#59 [Refactor] S3 디렉토리 구조 변경
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/service/FeedbackService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/service/MemberService.java
  src/main/java/org/programmers/signalbuddyfinal/global/service/AwsFileService.java
  src/test/java/org/programmers/signalbuddyfinal/domain/feedback/service/FeedbackServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/member/service/MemberServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/global/service/AwsFileServiceTest.java
Labels: Refactor

#62 [Refactor] 토큰 관련 리팩터링
  build.gradle
  src/main/java/org/programmers/signalbuddyfinal/domain/auth/controller/AuthController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/auth/dto/LoginRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/auth/service/AuthService.java
  src/main/java/org/programmers/signalbuddyfinal/global/config/RedisConfig.java
  src/main/java/org/programmers/signalbuddyfinal/global/config/SecurityConfig.java
  src/main/java/org/programmers/signalbuddyfinal/global/security/CustomAuthenticationProvider.java
  src/main/java/org/programmers/signalbuddyfinal/global/security/basic/CustomUserDetailsService.java
  src/main/java/org/programmers/signalbuddyfinal/global/security/exception/CustomAuthenticationEntryPoint.java
  src/main/java/org/programmers/signalbuddyfinal/global/security/filter/JwtAuthorizationFilter.java
  src/main/java/org/programmers/signalbuddyfinal/global/security/jwt/JwtService.java
  src/main/java/org/programmers/signalbuddyfinal/global/security/jwt/JwtUtil.java
  src/main/java/org/programmers/signalbuddyfinal/global/security/jwt/RefreshToken.java
  src/main/java/org/programmers/signalbuddyfinal/global/security/jwt/RefreshTokenRepository.java
  src/main/java/org/programmers/signalbuddyfinal/global/security/jwt/TokenErrorCode.java
  src/test/java/org/programmers/signalbuddyfinal/domain/auth/controller/AuthControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/global/config/RedisConfig.java
Labels: Bug, Refactor

#63 [Refactor] 최근경로 양방향 매핑 해제
  src/main/java/org/programmers/signalbuddyfinal/domain/bookmark/entity/Bookmark.java
  src/main/java/org/programmers/signalbuddyfinal/domain/bookmark/service/BookmarkService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/recentpath/controller/RecentPathController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/recentpath/dto/RecentPathLinkRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/recentpath/repository/RecentPathRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/recentpath/service/RecentPathService.java
  src/test/java/org/programmers/signalbuddyfinal/domain/recentpath/controller/RecentPathControllerTest.java
Labels: Feature, Refactor

#66 [Refactor] 프로필 이미지 http 메서드 변경
  src/main/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberController.java
  src/test/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberControllerTest.java
Labels: Refactor

#67 [Feature] 포스드잇 등록, 수정, 삭제 구현
  src/main/java/org/programmers/signalbuddyfinal/domain/postit/controller/PostItController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postit/dto/PostItCreateRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postit/dto/PostItRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postit/dto/PostItResponse.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postit/entity/Danger.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postit/entity/Postit.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postit/exception/PostItErrorCode.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postit/mapper/PostItMapper.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postit/repository/PostItRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postit/service/PostItService.java
  src/main/java/org/programmers/signalbuddyfinal/global/service/AwsFileService.java
  src/test/java/org/programmers/signalbuddyfinal/domain/admin/repository/AdminMemberRepositoryTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/postit/controller/PostItControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/postit/service/PostItServiceTest.java
Labels: Feature, Refactor, Test

#74 [Refactor] 로그인 성공 후 응답 수정
  src/main/java/org/programmers/signalbuddyfinal/domain/auth/service/AuthService.java
Labels: Refactor

#78 [Fix] 프로필 이미지 변경 리턴 데이터 수정
  src/main/java/org/programmers/signalbuddyfinal/domain/member/service/MemberService.java
Labels: Refactor

#82 [Fix] 쿠키 설정 변경
  src/main/java/org/programmers/signalbuddyfinal/domain/auth/dto/EmailRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/auth/service/AuthService.java
  src/main/java/org/programmers/signalbuddyfinal/global/config/SecurityConfig.java
Labels: Bug

#80 [Feature] 포스트잇 해결 상태 변경 기능 구현
  src/main/java/org/programmers/signalbuddyfinal/domain/admin/controller/AdminWebController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/service/MemberService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postit/batch/JobConfig.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postit/batch/PostItCustomReader.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postit/batch/Scheduler.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postit/controller/PostItController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postit/entity/Postit.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postit/service/PostItComplete.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postit/service/PostItService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postitsolve/entity/PostitSolve.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postitsolve/repository/PostitSolveRepository.java
  src/test/java/org/programmers/signalbuddyfinal/domain/postit/controller/PostItControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/postit/service/PostItServiceTest.java
Labels: Docs, Feature

#87 [Refactor] 관리자 회원 관리 코드 리펙터링
  src/main/java/org/programmers/signalbuddyfinal/domain/admin/controller/AdminController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/admin/dto/AdminMemberRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/admin/dto/MemberFilterRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/admin/dto/enums/Periods.java
Labels: Refactor

#89 [Refactor] 코드 리뷰 피드백
  src/main/java/org/programmers/signalbuddyfinal/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/bookmark/repository/BookmarkRepositoryCustomImpl.java
  src/main/java/org/programmers/signalbuddyfinal/domain/bookmark/service/BookmarkService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/service/MemberService.java
  src/test/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/member/service/MemberServiceTest.java
Labels: Refactor

#90 [Fix] 잘못 병합된 코드 수정
  src/main/java/org/programmers/signalbuddyfinal/domain/member/service/MemberService.java
Labels: Refactor

#96 [Feature] 관리자 포스트잇 관리 기능 구현
  src/main/java/org/programmers/signalbuddyfinal/domain/admin/controller/AdminPostItController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/admin/dto/AdminPostItResponse.java
  src/main/java/org/programmers/signalbuddyfinal/domain/admin/dto/PostItFilterRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/admin/dto/enums/Deleted.java
  src/main/java/org/programmers/signalbuddyfinal/domain/admin/service/AdminPostItService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/member/repository/CustomMemberRepositoryImpl.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postit/controller/PostItController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postit/exception/PostItErrorCode.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postit/repository/CustomPostItRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postit/repository/CustomPostItRepositoryImpl.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postit/repository/PostItRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/postit/service/PostItComplete.java
  src/test/java/org/programmers/signalbuddyfinal/domain/admin/controller/AdminPostItControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/admin/repository/AdminPostItRepositoryTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/admin/service/AdminPostItServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/postit/service/PostItServiceTest.java
Labels: Feature

#97 [Feature] 피드백 검색 조건 추가
  build.gradle
  src/main/java/org/programmers/signalbuddyfinal/domain/admin/controller/AdminFeedbackController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/admin/service/AdminFeedbackService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/controller/FeedbackController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/repository/CustomFeedbackRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/repository/CustomFeedbackRepositoryImpl.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/repository/FeedbackRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback/service/FeedbackService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback_report/controller/FeedbackReportController.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback_report/dto/FeedbackReportSearchRequest.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback_report/repository/CustomFeedbackReportRepository.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback_report/repository/CustomFeedbackReportRepositoryImpl.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback_report/service/FeedbackReportService.java
  src/main/java/org/programmers/signalbuddyfinal/domain/feedback_summary/repository/CustomFeedbackSummaryRepositoryImpl.java
  src/main/java/org/programmers/signalbuddyfinal/global/constant/SearchTarget.java
  src/main/java/org/programmers/signalbuddyfinal/global/constant/SearchTargetConverter.java
  src/main/java/org/programmers/signalbuddyfinal/global/util/QueryDslUtils.java
  src/test/java/org/programmers/signalbuddyfinal/domain/admin/controller/AdminFeedbackControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/admin/service/AdminFeedbackServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/feedback/controller/FeedbackControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/feedback/repository/FeedbackRepositoryImplTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/feedback/service/FeedbackServiceTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/feedback_report/controller/FeedbackReportControllerTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/feedback_report/repository/FeedbackReportRepositoryTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/feedback_summary/repository/CustomFeedbackSummaryRepositoryImplTest.java
  src/test/java/org/programmers/signalbuddyfinal/domain/feedback_summary/service/FeedbackSummaryServiceTest.java
Labels: Feature, Refactor
